spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/kara_db
spring.datasource.username=root
spring.datasource.password=041299

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8081

jwt.secret=sdf8s7df8s7df8s7df8s7df8s7df8s7df
jwt.expiration=86400000

gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=